package initialize

import (
	//_ "go-temp/docs"
	"go-temp/global"
	"go-temp/middleware"
	"go-temp/router"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// 初始化总路由

func Routers() *gin.Engine {
	var Router = gin.Default()
	Router.StaticFS(global.CONFIG.Local.Path, http.Dir(global.CONFIG.Local.Path)) // 为用户头像和文件提供静态地址
	// Router.Use(middleware.LoadTls())  // 打开就能玩https了
	global.LOG.Info("use middleware logger")
	// 跨域
	//Router.Use(middleware.Cors()) // 如需跨域可以打开
	global.LOG.Info("use middleware cors")
	Router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	global.LOG.Info("register swagger handler")
	// 方便统一添加路由组前缀 多服务器上线使用

	//获取路由组实例
	userRouter := router.RouterGroupApp.User
	PublicGroup := Router.Group("")
	{
		userRouter.InitBaseRouter(PublicGroup) // 注册基础功能路由 不做鉴权
	}
	PrivateGroup := Router.Group("")
	PrivateGroup.Use(middleware.JWTAuth()).Use(middleware.CasbinHandler())
	{
		userRouter.InitUserRouter(PrivateGroup) // 注册用户路由
		//userRouter.InitApiRouter(PrivateGroup)                    // 注册功能api路由
		/*systemRouter.InitJwtRouter(PrivateGroup)                    // jwt相关路由
		systemRouter.InitMenuRouter(PrivateGroup)                   // 注册menu路由
		systemRouter.InitEmailRouter(PrivateGroup)                  // 邮件相关路由
		systemRouter.InitSystemRouter(PrivateGroup)                 // system相关路由
		systemRouter.InitCasbinRouter(PrivateGroup)                 // 权限相关路由
		systemRouter.InitAutoCodeRouter(PrivateGroup)               // 创建自动化代码
		systemRouter.InitAuthorityRouter(PrivateGroup)              // 注册角色路由
		systemRouter.InitSysDictionaryRouter(PrivateGroup)          // 字典管理
		systemRouter.InitSysOperationRecordRouter(PrivateGroup)     // 操作记录
		systemRouter.InitSysDictionaryDetailRouter(PrivateGroup)    // 字典详情管理
		exampleRouter.InitFileUploadAndDownloadRouter(PrivateGroup) // 文件上传下载功能路由
		exampleRouter.InitExcelRouter(PrivateGroup)                 // 表格导入导出
		exampleRouter.InitSimpleUploaderRouter(PrivateGroup)        // 断点续传（插件版）
		exampleRouter.InitCustomerRouter(PrivateGroup)              // 客户路由*/

		// Code generated by go-temp Begin; DO NOT EDIT.
		//autocodeRouter.InitSysAutoCodeExampleRouter(PrivateGroup)
		// Code generated by go-temp End; DO NOT EDIT.
	}
	global.LOG.Info("路由注册完成")
	return Router
}
